services:
  app:
    image: node:14  # Imagen base para tu aplicación Node.js, ajusta según tu versión
    env:
      PORT: ${{ env.PORT }}  # Puerto donde se ejecutará tu aplicación, configurado automáticamente por Railway
      DB_HOST: ${{ env.DB_HOST }}
      DB_USER: ${{ env.DB_USER }}
      DB_PASSWORD: ${{ env.DB_PASSWORD }}
      DB_NAME: ${{ env.DB_NAME }}
      DB_PORT: ${{ env.DB_PORT }}
    # Aquí puedes configurar cualquier otro servicio necesario para tu aplicación, como Redis, etc.
    
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    name: mysql-data-${{ deploymentId }}  # Nombre del volumen para persistencia de datos de MySQL
